
spring:
  application:
    name: tutv-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true